### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by janwirth** [allenRoyston/ng-parallax#2]
background-position is very slow. Creating a second element using transforms instead makes more sense.

**Comment by allenJynRoyston** [comment]
If you wanna make a branch and a pull request i'll totally merge it.

**Comment by janwirth** [comment]
Nice!

**Comment by janwirth** [comment]
Would it make sense to extend the scope of this project so that you can apply the parallax effect to any kind of element?
Or possibly just start wrapping skrollr in a directive :/

**Comment by allenJynRoyston** [comment]
I do believe that it can already be applied to any element already.  My memory is a little rusty.

**Comment by janwirth** [comment]
Oh i was too imprecise. Forget about that. I will use skrollr and leave this be the way that is. Sorry for the disruption.

**Comment by allenJynRoyston** [comment]
No worries man.  If there are any other issues feel free to let me know =D

**Comment by janwirth** [comment]
What do you think about wrapping [skrollr](https://github.com/Prinzhorn/skrollr)?
The main need to integrate it are [dom chages that need to be compiled by skrollr](http://stackoverflow.com/questions/23715337/integrating-skrollr-w-angularjs-single-page-app) somehow.

**Comment by allenJynRoyston** [comment]
I'm not sure I understand your question.  Is this what you're looking for?

https://github.com/thisissoon/angular-skrollr

**Comment by janwirth** [comment]
yes, exactly :sweat_smile:
