### ISSUE TITLE
Background cover

### ISSUE THREAD

**Issue by edencorbin** [allenRoyston/ng-parallax#7]
This is a great simple parallax plugin. I'm trying to modify so that the parallax image will stretch/fill to div size/browser size. I tried adding this to the js which didn't change anything, any ideas?

```
          bgObj.style.backgroundSize="cover";
          bgObj.style.width = "100%";
```

**Comment by ealbinu** [comment]
Use CSS w/ !important:

#bgObj{
 background-size: cover !important;
}

**Comment by cescoferraro** [comment]
@ealbinu using you solution the image indeed get the way I want but then I have no parallax affect!
Any workaround?

**Comment by edencorbin** [comment]
I never tested and custom rolled my own solution in the end, going to go ahead and close this one.

**Comment by cescoferraro** [comment]
@edencorbin whats your custom rolled solution? Can you share?
